numbers = [3,4,5,6,7,8,13,17]
print(numbers[0])
print(numbers[5])
print(numbers[-1])
print(numbers[-6])
print(numbers[1:5])
print(numbers[:4])
print(numbers[3:])
print(numbers[:])
print(numbers[5:-1])
print(numbers[3:5:-2])
print(numbers[5:0:2])
print(numbers[5:0:-2])
numbers.append(10)
print(numbers[:])
numbers.insert(5,121)
print(numbers[:])
numbers.remove(10)
print(numbers[:])
numbers.pop()
print(numbers[:])
ln = numbers.count(5)
number2 = numbers.copy()
print(ln)
print(number2[:])
numbers.clear()
print(numbers)
